name: autofix.ci # needed to securely identify the workflow

on:
    push:
        branches:
            - main
    pull_request:

permissions:
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}

env:
    BUN_VERSION: 1.2.1
jobs:
    autofix:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: 1.2.1

            - run: bun install --frozen-lockfile
            - run: bun format

            - name: Fix typos
              uses: crate-ci/typos@v1.26.8
              with:
                  write_changes: true
            - name: remove Typos binary
              run: rm -f ./typos

            - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
