# Checks test suite source code itself. Does not actually run ecosystem tests.
name: Check

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    BUN_VERSION: 1.2.1

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: ${{ env.BUN_VERSION }}
            - run: bun install --frozen-lockfile
            - run: bun format --check
            - run: bun lint
            - run: bun check

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: ${{ env.BUN_VERSION }}
            - name: Install shellcheck
              run: sudo apt-get install -y shellcheck
            - run: bun install --frozen-lockfile
            - run: bun test
